package com.example.athometfgandroidcarloshernandez.common

object ConstantesError {
    const val NO_HAY_HABITACIONES_PARA_MUEBLE = "No hay habitaciones para añadir muebles"
    const val ERROR_DECODIFICAR_IMAGEN = "Error al decodificar la imagen"
    const val IMAGEN_OBLIGATORIA = "Suba una foto del producto"
    const val NO_ES_PROPIETARIO: String = "No eres propietario de este cajón"
    const val NOMBRE_CANTIDAD_OBLIGATORIO = "Nombre y cantidad son obligatorios"
    const val ERROR_NUMERO_ENTERO = "La cantidad debe ser un número entero"
    const val PRODUCTO_EXISTENTE = "El producto ya existe"
    const val ERROR_CODIGO : String = "Código inválido"
    const val ERROR_USUARIO_NO_ENCONTRADO: String = "Usuario no encontrado"
    const val ERROR_NO_CONFIRMADO: String = "Usuario no validado, confirme el correo"
    const val YA_VOTADO: String="Ya votaste en este evento"
    const val ERROR_VOTAR_EVENTO: String="Error al votar"
    const val NO_HAY_CAJON_QUE_BORRAR: String="No hay cajón que borrar"
    const val NO_SE_PUEDE_BORRAR_CAJON: String="No se puede borrar el cajón, borra uno de tu propiedad"
    const val ERROR_BORRAR_CAJON: String = "Error al borrar el cajón"
    const val TELEFONO_NO_VALIDO: String = "Escriba un número de teléfono válido"
    const val CORREO_NO_VALIDO: String = "Escriba un correo válido"
    const val CASA_NO_SELECCIONADA: String = "Debe seleccionar una casa para continuar"
    const val NO_HAY_CASA: String= "No hay casa existente"
    const val ERROR_REFRESCAR_TOKEN: String = "Error al refrescar el token"
    const val ERROR_INICIO_SESION: String = "Error al iniciar sesión"
    const val GET_USUARIOS_ERROR: String = "Error al obtener los usuarios"
    const val ERROR_AGREGAR_CAJON: String = "Error al añadir el cajón"
    const val ERROR_AGREGAR_MUEBLE: String = "Error al añadir el mueble"
    const val ERROR_AGREGAR_HABITACION: String="Error al añadir la habitacion"
    const val NO_ESTA_LOGUEADO: String = "Debe iniciar sesión para acceder a esta sección"
    const val GET_HABITACIONES_ERROR: String = "Error al obtener los datos de las habitaciones"
    const val GET_EVENTOS_ERROR: String = "Error al obtener los eventos"
    const val CREAR_EVENTO_ERROR: String =  "Error al crear el evento"
    const val HORA_ANTERIOR_ERROR: String ="La hora de inicio debe ser anterior a la hora de fin."
    const val FORMATO_FECHA_ERROR: String = "Formato de hora inválido. Use el formato HH:mm."
    const val BASE_DE_DATOS_ERROR = "Error en la base de datos"
    const val CAMPO_VACIO_ERROR = "Rellene todos los campos"
}