package com.example.inhometfgandroidcarloshernandez.common

object ConstantesPaths {
    const val ANIO_QUERY = "anio"
    const val MES_QUERY = "mes"
    const val DIA_QUERY = "dia"
    const val IDCASA_QUERY = "idCasa"
    const val LOGIN = "login"
    const val LOGIN_URL = "/login"
    const val REFRESH_TOKEN_URL = "/refreshToken"
    const val ESTADOS = "casa/pantallaEstados"
    const val CAMBIAR_ESTADO = "casa/cambiarEstado"
    const val GET_EVENTOS_MES = "calendario/getEventosMes"
    const val GET_EVENTOS_DIA = "calendario/getEventosDia"
    const val CREAR_EVENTO = "calendario/crearEvento"
    const val INMUEBLES= "inmuebles/pantallaInmuebles"
    const val AGREGAR_HABITACION = "inmuebles/agregarHabitacion"
    const val AGREGAR_MUEBLE = "inmuebles/agregarMueble"
    const val AGREGAR_CAJON = "inmuebles/agregarCajon"
    const val GET_USUARIOS="inmuebles/getUsuarios"
    const val REFRESH_TOKEN="login/refreshToken"
    const val GET_CASAS="casa/getCasas"
    const val REGISTRO= "registro"
    const val AGREGAR_CASA= "casa/agregarCasa"
    const val UNIRSE_CASA= "casa/unirseCasa"
}